frontend/micro-ui/web/micro-ui-internals/example/package.json, frontend/micro-ui/web/micro-ui-internals/packages/modules/Project/package.json, frontend/micro-ui/web/micro-ui-internals/packages/modules/Project/src/configs/createProjectConfigMUKTA.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/Project/src/utils/createProjectUtils.js, frontend/micro-ui/web/micro-ui-internals/packages/react-components/src/hoc/FormComposer.js, frontend/micro-ui/web/micro-ui-internals/packages/react-components/src/molecules/ApiDropdown.js
Reverts odisha-muktasoft/MUKTA_IMPL#7
=> Revert "PFM-3896 : Updated the code to handle locality and ward using config"

frontend/micro-ui/web/docker/nginx.conf
=> Security Fixes

frontend/micro-ui/web/micro-ui-internals/example/package.json, frontend/micro-ui/web/package.json
=> Update DSS module to latest version 1.5.42

backend/expense/src/main/java/org/egov/digit/expense/repository/rowmapper/BillRowMapper.java
=> Add additionalDetails to payee in expense service

backend/expense/src/main/java/org/egov/digit/expense/repository/rowmapper/BillRowMapper.java
=> getAdditionalDetails refactoring

frontend/micro-ui/web/micro-ui-internals/example/package.json, frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/utils/dss/index.js, frontend/micro-ui/web/micro-ui-internals/packages/react-components/src/atoms/svgindex.js, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
=> Update dss and css version

frontend/micro-ui/web/micro-ui-internals/example/package.json, frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
=> updated DSS and CSS

frontend/micro-ui/web/micro-ui-internals/example/package.json, frontend/micro-ui/web/package.json
=> Update DSS version

frontend/micro-ui/web/micro-ui-internals/packages/modules/Contracts/src/pages/employee/ViewContractDetails.js
PFM-4577 Not showing action button for few Work Order accepted applications to create purchase bill or Time Extension
=> PFM-4577 Not showing action button for few Work Order accepted applications to create purchase bill or Time Extension

frontend/micro-ui/web/micro-ui-internals/packages/Mukta/src/configs/UICustomizations.js
PFM-4557 project name is not showing proper in search screen if text is long
=> PFM-4557 project name is not showing proper in search screen if text is long

frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/public/index.html
PFM-4795 updated css package version
=> PFM-4795 updated css package version

frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/public/index.html
PFM-4795 Updated css package versions
=> PFM-4795 Updated css package versions

frontend/micro-ui/web/public/index.html
PFM-4305 Added Style sheet for mukta specific
=> PFM-4305 Added Style sheet for mukta specific

frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/public/index.html
PFM-4936 CSS Version upgrade in MUKTA IMPL, breaking other CSS
=> PFM-4936 CSS Version upgrade in MUKTA IMPL, breaking other CSS

frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/utils/debouncing.js
updating the value of 500 to initial value till disabling of submit button is implemented
=> PFM-5477 : Update debouncing.js

backend/measurement-service/src/main/java/org/egov/works/measurement/config/MBServiceConfiguration.java, backend/measurement-service/src/main/java/org/egov/works/measurement/config/ServiceConstants.java, backend/measurement-service/src/main/java/org/egov/works/measurement/service/NotificationService.java, backend/measurement-service/src/main/java/org/egov/works/measurement/web/models/WorksSmsRequest.java, backend/measurement-service/src/main/resources/application.properties
Implemented Sms notification for measurement-service please review the code and update if any changes needs to be fixed
=> Implemented Sms Notification for measurement-service

utilities/bulk-upload/src/main/java/org/egov/config/Configuration.java, utilities/bulk-upload/src/main/java/org/egov/service/BulkUploadService.java, utilities/bulk-upload/src/main/java/org/egov/util/BulkUploadUtil.java, utilities/bulk-upload/src/main/java/org/egov/web/controllers/BulkUploadController.java, utilities/bulk-upload/src/main/java/org/egov/web/models/MdmsCriteriaReqV2.java, utilities/bulk-upload/src/main/java/org/egov/web/models/MdmsCriteriaV2.java, utilities/bulk-upload/src/main/resources/application.properties
Refactored Bulk Upload Service updated and merged all the code into one service and controller of bulk upload and update,
Please review the code and let me know if anythings needs to be fixed
=> Refactored Bulk Upload Service Updated Code of Bulk Update

backend/contracts/src/main/java/org/egov/works/service/NotificationService.java, backend/contracts/src/main/java/org/egov/works/util/HRMSUtils.java
=> Updated code for TE SMS

build/build-config.yml
Added Builds config for sms-adapter for master branch
=> Added Builds config for sms-adapter

reference-adapters/sms-adapter/src/main/resources/application.properties
=> Updated hrms host

reference-adapters/sms-adapter/src/main/java/org/egov/works/config/NotificationServiceConfiguration.java
Commented Mukta SMS topic config
=> Commented Mukta SMS topic config

backend/measurement-service/src/main/java/org/egov/works/measurement/enrichment/MeasurementEnrichment.java, backend/measurement-service/src/main/java/org/egov/works/measurement/service/MeasurementService.java, backend/measurement-service/src/main/java/org/egov/works/measurement/util/MeasurementServiceUtil.java, backend/measurement-service/src/main/java/org/egov/works/measurement/web/models/Document.java, backend/measurement-service/src/main/java/org/egov/works/measurement/web/models/Measurement.java
Added isActive key in the additonalDetails map to filter the deleted file in search api call
=> Made changes to remove files in MB

backend/measurement-service/src/main/java/org/egov/works/measurement/util/MeasurementServiceUtil.java
Refactored code for mb service added a isActive check before updated documents isActive status
=> Refactored code

frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/package.json
Reverts odisha-muktasoft/MUKTA_IMPL#324
=> Revert "Build publishing fix, changes done in package json"

reference-adapters/sms-adapter/src/main/java/org/egov/works/models/ContractCriteria.java, reference-adapters/sms-adapter/src/main/java/org/egov/works/models/ContractRequest.java, reference-adapters/sms-adapter/src/main/java/org/egov/works/models/Estimate.java, reference-adapters/sms-adapter/src/main/java/org/egov/works/models/EstimateDetail.java, reference-adapters/sms-adapter/src/main/java/org/egov/works/models/EstimateRequest.java, reference-adapters/sms-adapter/src/main/java/org/egov/works/models/EstimateResponse.java, reference-adapters/sms-adapter/src/main/java/org/egov/works/models/LineItems.java, reference-adapters/sms-adapter/src/main/java/org/egov/works/models/Pagination.java, reference-adapters/sms-adapter/src/main/java/org/egov/works/models/Party.java
Updated Pojo's of SMS-Adapter to the latest one please review/merge/deploy to test the adapter service
=> Updated POJO's

frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/package.json
Reverts odisha-muktasoft/MUKTA_IMPL#338
=> Revert "fix done in package to publish packages version in npm"

frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/package.json
Reverts odisha-muktasoft/MUKTA_IMPL#341
=> Revert "Build fix for publishing of version"

frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/package.json
Reverts odisha-muktasoft/MUKTA_IMPL#344
=> Build fix for publishing of version - 1

frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/package.json
Reverts odisha-muktasoft/MUKTA_IMPL#345
=> Revert "Build fix for publishing of version - 1"

frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/package.json
Reverts odisha-muktasoft/MUKTA_IMPL#348
=> Revert "build fix to publish expenditure module"

frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/package.json
Reverts odisha-muktasoft/MUKTA_IMPL#352
=> Revert "Did the build fix for publishing of expenditure module"

frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/package.json
Reverts odisha-muktasoft/MUKTA_IMPL#363
=> Revert "Updating the package json in order to fix the error of publishing to npm"

frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/package.json
Reverts odisha-muktasoft/MUKTA_IMPL#367
=> Revert "Updated the package in order to publish expenditure module"

frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/package.json
Reverts odisha-muktasoft/MUKTA_IMPL#370
=> Revert "Publish fix for expenditure module"

backend/organisation/src/main/java/org/egov/service/OrganisationEnrichmentService.java, backend/organisation/src/main/java/org/egov/util/WorkflowUtil.java, backend/organisation/src/main/java/org/egov/web/models/ProcessInstance.java, backend/organisation/src/main/java/org/egov/web/models/ProcessInstanceRequest.java, backend/organisation/src/main/java/org/egov/web/models/Workflow.java
Updated Workflow model and added ProcessInstance, ProcessInstanceRequest  since Workflow from coremodels was removed
=> Updated Workflow model

frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/package.json
Reverts odisha-muktasoft/MUKTA_IMPL#374
=> Revert "Publish fix for expenditure"

reference-adapters/sms-adapter/src/main/java/org/egov/works/config/Constants.java, reference-adapters/sms-adapter/src/main/java/org/egov/works/service/EstimateNotificationService.java
=> Refactored SMS-Adapter

frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/package.json
Reverts odisha-muktasoft/MUKTA_IMPL#394
=> Revert "doing the changes for the build fix in order to publish at npm"

reference-adapters/sms-adapter/src/main/java/org/egov/works/service/EstimateNotificationService.java
Please Check this I have updated the key values to of projectDetails It was unable to parse with previous one
=> Updated Json properties

reference-adapters/sms-adapter/src/main/java/org/egov/works/service/EstimateNotificationService.java
Removed getProjectDetails() from EstimateNotificationService because the funcitonality was already implemented in projectutils class
=> Removed getProjectDetails Method

frontend/micro-ui/web/micro-ui-internals/packages/modules/RateAnalysis/src/components/SORDetailsTemplate.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/RateAnalysis/src/components/rateAmountGroup.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/RateAnalysis/src/components/ratecardbutton.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/RateAnalysis/src/configs/ViewRateAnalysisConfig.js
feed back UI changes :
1. In view rate analysis table column width for code reduced.
2. hard coded CUM in  the button group is changed as per the UOM
3. info card width increased to 100%
=> feed back changes

.coderabbit.yaml
=> Code Rabbit Configurations

.coderabbit.yaml
=> Code Rabbit Configurations-v2

frontend/micro-ui/web/micro-ui-internals/packages/modules/Estimate/src/components/ViewStatement.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/Estimate/src/pageComponents/ViewAnalysisStatement.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/Estimate/src/pages/employee/ViewAnalysisStatementPage.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/Measurement/src/configs/viewUtilConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/Measurement/src/pages/employee/viewUtilization.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/RateAnalysis/src/components/SORDetailsTemplate.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/RateAnalysis/src/components/rateAmountGroup.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/RateAnalysis/src/pages/employee/CreateRateAnalysis.js
Reverts odisha-muktasoft/MUKTA_IMPL#480
=> Revert "4188 consolidated table"

frontend/micro-ui/web/micro-ui-internals/packages/modules/Estimate/src/components/ConsolidatedTable.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/Estimate/src/components/ViewStatement.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/RateAnalysis/src/pages/employee/ViewRateAnalysis.js
Table style changed in view utilisation and analysis screen
=> Mb util uat

frontend/micro-ui/web/micro-ui-internals/packages/modules/Estimate/src/pageComponents/searchTemplate.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/Measurement/src/Module.js
estimate template changes done as per the mdms schema
=> estimate template reworked

backend/rate-analysis/src/main/java/org/egov/works/config/Configuration.java, backend/rate-analysis/src/main/java/org/egov/works/kafka/RateAnalysisConsumer.java, backend/rate-analysis/src/main/java/org/egov/works/service/MdmsService.java, backend/rate-analysis/src/main/resources/application.properties
This PR is as per the changes done by the works team
https://github.com/egovernments/DIGIT-Works/commit/8ef84f273e5311b635872f7a40b87260c79e1cbf
=> [UCEM-462]-Mdms v2 consumer changes

frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/package.json
Reverts odisha-muktasoft/MUKTA_IMPL#608
=> Revert "Doing the publish fix"

.github/workflows/publishUIPackages.yml
Reverts odisha-muktasoft/MUKTA_IMPL#606
=> Revert "Update publishUIPackages.yml"

frontend/micro-ui/web/micro-ui-internals/packages/react-components/package.json
Updating react components package.json
=> UCEM-725 : Update package.json

frontend/works_shg_app/lib/widgets/mb/multi_image.dart
1. SHG web file issue is fixed
=> platform image issue is resolved

frontend/works_shg_app/.env, frontend/works_shg_app/lib/blocs/app_initilization/home_screen_bloc.dart, frontend/works_shg_app/lib/blocs/employee/mb/project_type.dart, frontend/works_shg_app/lib/blocs/organisation/org_search_bloc.dart, frontend/works_shg_app/lib/blocs/wage_seeker_registration/wage_seeker_locality_bloc.dart, frontend/works_shg_app/lib/blocs/wage_seeker_registration/wage_seeker_location_bloc.dart, frontend/works_shg_app/lib/pages/org_profile.dart, frontend/works_shg_app/lib/pages/service_requests/service_requests.dart, frontend/works_shg_app/lib/pages/view_muster_rolls.dart, frontend/works_shg_app/lib/services/urls.dart
1. boundary service url replaced
2. mdms url changed
=> Boundary v2 1 1

frontend/works_shg_app/lib/pages/employee/mb_config_warning.dart, frontend/works_shg_app/lib/pages/employee/mb_detail_page.dart, frontend/works_shg_app/lib/pages/employee/mb_muster_screen.dart, frontend/works_shg_app/lib/pages/wage_seeker_registration/financial_details.dart, frontend/works_shg_app/lib/utils/string_extension.dart
Reverts odisha-muktasoft/MUKTA_IMPL#793
=> Revert "Uat new component"

frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/services/molecules/Attendance/View.js, frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/services/molecules/Organisation/View.js
Reverts odisha-muktasoft/MUKTA_IMPL#813
=> Revert "masked ward in org details"

frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/services/molecules/Attendance/View.js, frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/services/molecules/Organisation/View.js
Reverts odisha-muktasoft/MUKTA_IMPL#815
=> Revert "Revert "masked ward in org details""
